### PR TITLE
ADD secondary OK buttons in addition to Esc: F10 and Backspace

### PR DESCRIPTION
**Pull request by allanlaal**
adds #5

### CODE REVIEW

**Comment by allanlaal** [comment]
closes #5

**Comment by allanlaal** [comment]
tested. works!

**Comment by martinwhitaker** [comment]
1. I'm not in favour of adding multiple alternatives - I like to keep things simple. Note that the function keys already have an alternative - the number keys (which I have now documented in the README) - so you get two for the price of one with F10.
2. Backspace already has an abstraction ('\b') so we don't need to define another one.
3. The comments in the header files describe the API to the associated 'C' file (when I find time I will add Doxygen formatting). The user does not need to know that the underlying implementation uses ASCII codes.

**Comment by allanlaal** [comment]
1. so ESC is currently the only key that does not have an alternative? :)

**Comment by martinwhitaker** [comment]
No, Enter, Backspace, and 'A' to 'F' don't have alternatives (unless you have an extended keyboard with a second Enter key).

**Comment by martinwhitaker** [comment]
As no revised patch was forthcoming, I've implemented this myself.

**Pull request closed without merging**
